#ifndef DMTCP_H
#define DMTCP_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "dmip.h"
#include "dmtcp_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @file dmtcp.h
 * @brief DMOD TCP - Public API
 *
 * dmtcp builds/parses TCP segments (RFC 793) and implements a solid subset
 * of the RFC 793 state machine on top of dmip: the three-way handshake
 * (passive and active open), reliable in-order data transfer with a
 * fixed-size sliding window and a retransmission timer, graceful close
 * (FIN/ACK both directions), and RST generation/handling. Deliberately out
 * of scope: congestion control (no slow start/congestion avoidance - a
 * fixed window only), TCP options (no MSS negotiation/SACK/window
 * scaling/timestamps - inbound options are skipped, never interpreted),
 * and IPv6 send (the same missing-NDP gap dmip/dmicmp/dmudp already live
 * with - dmtcp can parse/checksum-validate an inbound IPv6 segment but
 * cannot complete a handshake over one). See docs/dmtcp.md for the full
 * rationale and the complete list of known gaps.
 *
 * Unlike dmudp (a single global port-binding table, no per-datagram state)
 * dmtcp needs real per-connection state - a TCB - since a TCP connection is
 * a long-lived, sequenced, mutable stream, not a stateless callback per
 * packet. There are therefore two tables: a listen table (port ->
 * dmtcp_accept_handler_t, dmudp_bind()-shaped) for passive opens still
 * waiting for their first SYN, and a connection table (4-tuple -> TCB) for
 * every connection that has at least started its handshake. See
 * dmtcp_listen()/_listen_any()/_unlisten() and dmtcp_connect() below.
 *
 * dmtcp registers dmtcp_handle_ip_packet() via
 * dmip_register_protocol(DMIP_PROTO_TCP, ...) in dmod_init() (see
 * src/dmtcp.c) - the same mechanism dmudp/dmicmp use for their own IP
 * protocol numbers. A matching segment (exact 4-tuple, or a SYN on a
 * listened port) is processed inline, synchronously, on whatever thread is
 * pumping the interface it arrived on (see dmip_protocol_handler_t in
 * dmip.h) - so a handler reacting to dmtcp_data_handler_t can call
 * dmtcp_send() right back without needing its own thread or queue, the
 * same reasoning dmudp/dmicmp give for their own inline delivery. The one
 * structural exception is retransmission: a segment that needs to be
 * resent because no ACK arrived in time has no inbound packet to piggyback
 * on, so that path runs on a dmosi_timer_t instead, in timer/interrupt
 * context - see docs/dmtcp.md's "Two lock contexts" section.
 *
 * A SYN (or any other segment) addressed to a port with no listener and no
 * matching connection gets a standard TCP RST, generated by dmtcp itself
 * via plain dmip_send() (RFC 793 §3.4) - unlike dmudp/dmicmp, dmtcp has its
 * own native error-signaling segment and therefore has no need for
 * dmicmp_v4_send_dest_unreachable(); dmicmp is not a dependency of this
 * module. A malformed or checksum-invalid segment is always dropped
 * silently, regardless of any table lookup - the same rule dmudp applies
 * to malformed UDP datagrams.
 *
 * dmtcp depends on dmip (dmip_send()/_v4_get_source_address() to transmit,
 * dmip_checksum() for the pseudo-header checksum, dmip_v4_parse_header()/
 * _v6_parse_header() to read the enclosing IP header, protocol
 * registration) and, transitively through it, dmroute (dmip_addr_t's real
 * definition) and dmnetif (dmnetif_iface_t) - dmtcp itself never calls a
 * dmroute_* /dmnetif_* function directly. Also depends on dmlist (the
 * listen table and the connection table) and dmosi (mutexes guarding both
 * tables and every TCB, plus dmosi_timer_t for retransmission/TIME_WAIT and
 * dmosi_get_tick_count() for initial sequence number generation). Segments
 * are built/parsed as raw byte buffers rather than packed C structs, same
 * reasoning dmip.c/dmudp.c document for themselves (dmod's minimal module
 * runtime gives no struct-packing guarantee).
 */

/* ============================================================================
 *                      Common header (RFC 793 §3.1)
 * ========================================================================== */

/**
 * @brief Length in bytes of a TCP header with no options
 *
 * dmtcp_build_header() always emits Data Offset = 5 (no options) -
 * dmtcp_parse_header() still honors a larger Data Offset on a received
 * segment (skipping past any options, which are not interpreted), reporting
 * the real header length via its `header_len` out param - the same shape
 * dmip_v4_parse_header() uses for IPv4 header options.
 */
#define DMTCP_HEADER_LEN 20u

/**
 * @brief TCP header control bits (the low 6 bits of the flags byte)
 *
 * No ECE/CWR - congestion control (and the ECN this module never sets) is
 * out of scope, see this file's top comment.
 */
#define DMTCP_FLAG_FIN 0x01u
#define DMTCP_FLAG_SYN 0x02u
#define DMTCP_FLAG_RST 0x04u
#define DMTCP_FLAG_PSH 0x08u
#define DMTCP_FLAG_ACK 0x10u
#define DMTCP_FLAG_URG 0x20u

/**
 * @brief Parsed TCP header fields (RFC 793 §3.1)
 *
 * dmtcp_build_header() ignores `checksum` (the caller computes and writes
 * it separately, over a pseudo-header + header + payload - see
 * dmtcp_v4_checksum_valid()/_v6_checksum_valid() - the same two-step shape
 * dmudp_build_header() uses and for the same reason: the checksum covers a
 * payload that doesn't exist yet at build_header() time).
 */
typedef struct
{
    uint16_t src_port;
    uint16_t dst_port;
    uint32_t seq_num;
    uint32_t ack_num;
    uint8_t  flags;             /**< DMTCP_FLAG_* bitmask */
    uint16_t window;
    uint16_t checksum;          /**< Parse output only - see above */
    uint16_t urgent_pointer;
} dmtcp_header_t;

/**
 * @brief Build a 20-byte TCP header (no options, no payload) into `buffer`
 *
 * @param buffer     Output buffer, must be at least DMTCP_HEADER_LEN bytes
 * @param buffer_len Size of `buffer` in bytes
 * @param header     Fields to encode
 *
 * @return 0 on success, -EINVAL on a NULL argument or too-small buffer
 */
dmod_dmtcp_api(1.0, int, _build_header, ( uint8_t* buffer, size_t buffer_len, const dmtcp_header_t* header ));

/**
 * @brief Parse a TCP header from `buffer`
 *
 * Unlike dmudp_parse_header(), this reports the header's real length via
 * `header_len` - a real peer's SYN will carry TCP options (MSS, window
 * scale, timestamps, SACK-permitted) that dmtcp does not interpret (see
 * this file's top comment) but must still skip correctly to find where the
 * payload starts.
 *
 * @param buffer     Received bytes, header first
 * @param length     Number of valid bytes in `buffer`, must be at least
 *                    DMTCP_HEADER_LEN
 * @param header     Output: parsed fields
 * @param header_len Output: the header's real length in bytes (Data Offset
 *                    * 4, which may exceed DMTCP_HEADER_LEN if the header
 *                    carries options). `buffer + *header_len` is where the
 *                    payload starts
 *
 * @return 0 on success, -EINVAL on a NULL argument or `length` shorter than
 *         DMTCP_HEADER_LEN, -EPROTO if the declared Data Offset is smaller
 *         than 5 or `*header_len` would exceed `length`
 */
dmod_dmtcp_api(1.0, int, _parse_header, ( const uint8_t* buffer, size_t length, dmtcp_header_t* header, size_t* header_len ));

/* ============================================================================
 *                      Checksum
 * ========================================================================== */

/**
 * @brief Check whether a received TCP-over-IPv4 segment's checksum is valid
 *
 * Same RFC 793 pseudo-header shape UDP uses (RFC 768's is nearly
 * identical) - source/destination address, zero byte, protocol,
 * TCP-segment length - except the protocol byte is DMIP_PROTO_TCP.
 *
 * Unlike UDP, TCP has no "0 means no checksum" allowance for either family
 * (RFC 793 has never had one) - a wire checksum of 0 is simply computed
 * and compared like any other value, for both IPv4 and IPv6. This is
 * simpler than dmudp's own checksum story, which has to special-case an
 * IPv4 wire value of 0 in its receive path.
 *
 * @param src_ip  Source address the segment arrived from (family must be
 *                 dmip_family_v4)
 * @param dst_ip  Destination address it arrived on (family must be
 *                 dmip_family_v4)
 * @param segment Received bytes, TCP header first
 * @param length  Number of valid bytes in `segment`, must be at least
 *                 DMTCP_HEADER_LEN
 *
 * @return true if the checksum matches the segment's contents
 */
dmod_dmtcp_api(1.0, bool, _v4_checksum_valid, ( const dmip_addr_t* src_ip, const dmip_addr_t* dst_ip, const uint8_t* segment, size_t length ));

/**
 * @brief Check whether a received TCP-over-IPv6 segment's checksum is valid
 *
 * RFC 8200 8.1: mandatory, same as IPv4 for TCP (see above) - there is no
 * family-dependent special case anywhere in dmtcp's checksum handling.
 *
 * @param src_ip  Source address (family must be dmip_family_v6)
 * @param dst_ip  Destination address (family must be dmip_family_v6)
 * @param segment Received bytes, TCP header first
 * @param length  Number of valid bytes in `segment`, must be at least
 *                 DMTCP_HEADER_LEN
 *
 * @return true if the checksum matches the segment's contents
 */
dmod_dmtcp_api(1.0, bool, _v6_checksum_valid, ( const dmip_addr_t* src_ip, const dmip_addr_t* dst_ip, const uint8_t* segment, size_t length ));

/* ============================================================================
 *                      Connection handle
 * ========================================================================== */

/**
 * @brief Opaque handle to one TCP connection (a TCB)
 *
 * There is no public dmtcp_conn_create(): a handle only ever comes from a
 * completed passive handshake (delivered via dmtcp_accept_handler_t - see
 * dmtcp_listen()) or from dmtcp_connect() (active open). dmtcp itself owns
 * both creation and destruction.
 *
 * @par Handle lifetime
 * A dmtcp_conn_t is valid from the moment it is handed to you until
 * exactly one of the terminal callbacks - on_closed, on_reset, or on_error
 * (see dmtcp_conn_callbacks_t) - returns; at that point the underlying TCB
 * is freed and the handle must never be used again, not even to read
 * dmtcp_conn_get_state(). Do not call any dmtcp_conn_*()/dmtcp_send()/
 * _close()/_abort() function on a handle from inside its own terminal
 * callback.
 */
typedef struct dmtcp_conn* dmtcp_conn_t;

/**
 * @brief RFC 793 §3.2 connection states
 *
 * dmtcp_state_closed/_listen exist for completeness but are never actually
 * observed through dmtcp_conn_get_state(): a real TCB only ever springs
 * into existence already past those two states (at dmtcp_state_syn_received
 * for a passive open, or dmtcp_state_syn_sent for dmtcp_connect()) - a
 * passive-open port reservation that hasn't seen a SYN yet is tracked in
 * the listen table (see dmtcp_listen()), not as a dmtcp_conn_t. The instant
 * a connection reaches dmtcp_state_closed internally, its terminal
 * callback fires and the TCB is freed in the same step - there is no
 * window in which a live handle reports this state.
 */
typedef enum
{
    dmtcp_state_closed = 0,
    dmtcp_state_listen,
    dmtcp_state_syn_sent,
    dmtcp_state_syn_received,
    dmtcp_state_established,
    dmtcp_state_fin_wait_1,
    dmtcp_state_fin_wait_2,
    dmtcp_state_close_wait,
    dmtcp_state_closing,
    dmtcp_state_last_ack,
    dmtcp_state_time_wait,
} dmtcp_state_t;

/* ============================================================================
 *                      Listening (passive open)
 * ========================================================================== */

/**
 * @brief First port dmtcp_listen_any() will consider (RFC 6335 dynamic/
 *        private range)
 */
#define DMTCP_PORT_EPHEMERAL_FIRST 49152u

/**
 * @brief Last port dmtcp_listen_any() will consider (RFC 6335 dynamic/
 *        private range)
 */
#define DMTCP_PORT_EPHEMERAL_LAST 65535u

/**
 * @brief Callback registered via dmtcp_listen()/_listen_any() to receive a
 *        newly-established, passively-opened connection
 *
 * Fires exactly once per connection, the moment its three-way handshake
 * completes (state SYN_RECEIVED -> ESTABLISHED) - `conn` is already fully
 * usable by the time this is called (dmtcp_send() works immediately).
 * Called inline, on whatever thread is pumping the interface the final
 * handshake ACK arrived on (see dmip_protocol_handler_t in dmip.h) - the
 * same delivery context dmudp_datagram_handler_t/dmicmp's echo reply use,
 * specifically so this handler can call dmtcp_conn_set_callbacks()
 * synchronously, before returning, to hook on_data/on_closed/on_reset/
 * on_error as tightly as possible - a segment for this connection arriving
 * before callbacks are registered is not otherwise held back or queued.
 *
 * @param conn      The newly-established connection
 * @param peer      Address of the remote peer
 * @param peer_port Port the remote peer connected from
 * @param iface     Interface the connection's final handshake ACK arrived on
 */
typedef void (*dmtcp_accept_handler_t)( dmtcp_conn_t conn, const dmip_addr_t* peer, uint16_t peer_port, dmnetif_iface_t iface );

/**
 * @brief Reserve `port` and register `handler` to receive every new
 *        incoming connection addressed to it
 *
 * @param port    TCP port to listen on, must be nonzero
 * @param handler Callback to invoke once per completed incoming handshake
 *
 * @return 0 on success, -EINVAL if `handler` is NULL or `port` is 0,
 *         -EEXIST if `port` is already listened (call dmtcp_unlisten()
 *         first if you mean to replace it), -ENOMEM if the registration
 *         itself could not be allocated
 */
dmod_dmtcp_api(1.0, int, _listen, ( uint16_t port, dmtcp_accept_handler_t handler ));

/**
 * @brief Reserve the first free port in the ephemeral range
 *        (DMTCP_PORT_EPHEMERAL_FIRST..DMTCP_PORT_EPHEMERAL_LAST) and
 *        register `handler` for it
 *
 * @param handler  Callback to invoke once per completed incoming handshake
 * @param out_port Output: the port that was reserved
 *
 * @return 0 on success (`*out_port` set), -EINVAL if `handler` or
 *         `out_port` is NULL, -EADDRNOTAVAIL if every port in the
 *         ephemeral range is already listened, -ENOMEM if the registration
 *         itself could not be allocated
 */
dmod_dmtcp_api(1.0, int, _listen_any, ( dmtcp_accept_handler_t handler, uint16_t* out_port ));

/**
 * @brief Undo dmtcp_listen()/_listen_any() - safe to call for a port that
 *        was never listened (a no-op)
 *
 * Only stops accepting NEW connections on `port` - any dmtcp_conn_t already
 * established from that listener lives on independently in the connection
 * table (closing a real listening socket never affects already-accepted
 * connections, and dmtcp mirrors that).
 *
 * @param port TCP port to release
 */
dmod_dmtcp_api(1.0, void, _unlisten, ( uint16_t port ));

/* ============================================================================
 *                      Connection callbacks and active open
 * ========================================================================== */

/**
 * @brief Fires once a dmtcp_connect()'d connection completes its handshake
 *        (SYN_SENT -> ESTABLISHED)
 *
 * Never fires for a passively-accepted connection - it is already
 * ESTABLISHED by the time dmtcp_accept_handler_t hands it to you. Leave
 * this NULL in a dmtcp_conn_callbacks_t used for dmtcp_listen()/
 * _listen_any().
 */
typedef void (*dmtcp_established_handler_t)( dmtcp_conn_t conn, void* user_data );

/**
 * @brief Fires for new in-order payload, and once more (with `data` NULL,
 *        `data_len` 0) the moment the peer's FIN is received
 *
 * `data`/`data_len` are borrowed, valid only for the duration of the call
 * (the same borrowing rule dmip_protocol_handler_t documents for its own
 * `packet`) - copy out anything you need to keep.
 *
 * The `data == NULL` call is the Berkeley-sockets "read() returns 0" EOF
 * convention, not a terminal callback: dmtcp_send() still works afterward,
 * right up until dmtcp_close() is called locally or the peer later sends a
 * RST (see dmtcp_closed_handler_t/dmtcp_reset_handler_t).
 */
typedef void (*dmtcp_data_handler_t)( dmtcp_conn_t conn, const uint8_t* data, size_t data_len, void* user_data );

/**
 * @brief TERMINAL: fires exactly once, for a graceful (non-RST) finish,
 *        immediately before the TCB is freed
 *
 * See "Handle lifetime" in dmtcp_conn_t's own doc comment.
 */
typedef void (*dmtcp_closed_handler_t)( dmtcp_conn_t conn, void* user_data );

/**
 * @brief TERMINAL: fires exactly once - the peer sent a RST, or
 *        dmtcp_abort() was called locally - immediately before the TCB is
 *        freed
 *
 * See "Handle lifetime" in dmtcp_conn_t's own doc comment.
 */
typedef void (*dmtcp_reset_handler_t)( dmtcp_conn_t conn, void* user_data );

/**
 * @brief TERMINAL: fires exactly once when dmtcp itself gives up on a
 *        connection, immediately before the TCB is freed
 *
 * Currently the only cause is the retransmission retry limit being
 * exceeded with nothing ever coming back from the peer - `error` is
 * -ETIMEDOUT. See "Handle lifetime" in dmtcp_conn_t's own doc comment.
 */
typedef void (*dmtcp_error_handler_t)( dmtcp_conn_t conn, int error, void* user_data );

/**
 * @brief Callbacks for one connection's lifecycle events
 *
 * Passed to dmtcp_connect() up front, or registered on an accepted
 * connection via dmtcp_conn_set_callbacks() (typically from inside the
 * dmtcp_accept_handler_t that received it). Any member left NULL is simply
 * never called.
 */
typedef struct
{
    dmtcp_established_handler_t on_established;
    dmtcp_data_handler_t        on_data;
    dmtcp_closed_handler_t      on_closed;
    dmtcp_reset_handler_t       on_reset;
    dmtcp_error_handler_t       on_error;
} dmtcp_conn_callbacks_t;

/**
 * @brief Actively open a TCP connection (RFC 793 active OPEN)
 *
 * Non-blocking and callback-driven, consistent with the rest of this
 * codebase - nothing here ever parks a thread waiting on the network.
 * Returns as soon as the initial SYN is built and sent; the actual outcome
 * ("did it work") arrives later via `callbacks->on_established` or one of
 * `{on_reset, on_error}`.
 *
 * @param dst        Destination address
 * @param dst_port   Destination port, must be nonzero
 * @param src_port   Local port to use, or 0 to pick one from the ephemeral
 *                    range (DMTCP_PORT_EPHEMERAL_FIRST..DMTCP_PORT_EPHEMERAL_LAST)
 * @param callbacks  Lifecycle callbacks (copied - the pointer need not
 *                    outlive this call). May be NULL to start the
 *                    connection with no callbacks registered yet (set them
 *                    later with dmtcp_conn_set_callbacks())
 * @param user_data  Opaque pointer passed back to every callback
 * @param out_conn   Output: the new connection's handle
 *
 * @return 0 on success (`*out_conn` set), -EINVAL (bad argument), -ENOSYS
 *         (`dst->family == dmip_family_v6` - no dmip_v6_send() yet, see
 *         this file's top comment), -EADDRINUSE (an explicit `src_port`
 *         collides with an existing connection's 4-tuple),
 *         -EADDRNOTAVAIL (ephemeral range exhausted), -ENOMEM, or
 *         whatever dmip_v4_get_source_address()/dmip_send() return for the
 *         very first SYN transmission attempt (-ENETUNREACH/-ENODEV/
 *         -EHOSTUNREACH/-EMSGSIZE/-EIO) - a synchronous failure on that
 *         first SYN tears the just-created TCB down and is reported here
 *         directly, unlike a later retransmission failure (which has no
 *         caller stack frame to report to, and instead counts toward the
 *         retry limit - see dmtcp_error_handler_t)
 */
dmod_dmtcp_api(1.0, int, _connect, ( const dmip_addr_t* dst, uint16_t dst_port, uint16_t src_port,
                                      const dmtcp_conn_callbacks_t* callbacks, void* user_data, dmtcp_conn_t* out_conn ));

/* ============================================================================
 *                      Per-connection API
 * ========================================================================== */

/**
 * @brief Replace a connection's callbacks/user_data
 *
 * Typically called once, from inside a dmtcp_accept_handler_t, to hook up
 * on_data/on_closed/on_reset/on_error on a freshly-accepted connection
 * (which starts with no callbacks registered). Safe to call again later to
 * change them.
 *
 * @return 0 on success, -EINVAL if `conn` is NULL/invalid
 */
dmod_dmtcp_api(1.0, int, _conn_set_callbacks, ( dmtcp_conn_t conn, const dmtcp_conn_callbacks_t* callbacks, void* user_data ));

/**
 * @brief Get the `user_data` most recently set for `conn`
 *
 * @return The stored pointer, or NULL if `conn` is NULL/invalid or no
 *         user_data was ever set
 */
dmod_dmtcp_api(1.0, void*, _conn_get_user_data, ( dmtcp_conn_t conn ));

/**
 * @brief Get a connection's current RFC 793 state
 *
 * @return The current state, or dmtcp_state_closed if `conn` is NULL/invalid
 */
dmod_dmtcp_api(1.0, dmtcp_state_t, _conn_get_state, ( dmtcp_conn_t conn ));

/**
 * @brief Get the local address/port a connection is using
 *
 * @return 0 on success, -EINVAL if `conn`/`out_addr`/`out_port` is NULL/invalid
 */
dmod_dmtcp_api(1.0, int, _conn_get_local_endpoint, ( dmtcp_conn_t conn, dmip_addr_t* out_addr, uint16_t* out_port ));

/**
 * @brief Get the remote peer's address/port for a connection
 *
 * @return 0 on success, -EINVAL if `conn`/`out_addr`/`out_port` is NULL/invalid
 */
dmod_dmtcp_api(1.0, int, _conn_get_peer_endpoint, ( dmtcp_conn_t conn, dmip_addr_t* out_addr, uint16_t* out_port ));

/**
 * @brief Queue `data` for delivery over `conn`
 *
 * Byte-stream semantics, NOT dmudp_send()'s all-or-nothing datagram
 * semantics: returns the number of bytes actually queued, which may be
 * less than `data_len` (a partial write, exactly like POSIX write()) if
 * the connection's outbound buffer doesn't have room for all of it.
 *
 * @param conn     Connection to send on
 * @param data     Data to queue
 * @param data_len Length of `data` in bytes
 *
 * @return Number of bytes actually queued (>= 0) on success, -EINVAL (bad
 *         argument), -ENOTCONN (`conn`'s state isn't ESTABLISHED or
 *         CLOSE_WAIT), -ESHUTDOWN (dmtcp_close() was already called on
 *         this connection - the local send side is done)
 */
dmod_dmtcp_api(1.0, int, _send, ( dmtcp_conn_t conn, const void* data, size_t data_len ));

/**
 * @brief Gracefully close a connection (sends a FIN)
 *
 * Idempotent - safe to call again on a connection already mid-close.
 * Always completes the local half-close state transition even if the
 * FIN's first transmission attempt fails (the retransmission timer retries
 * it) - the return value is a diagnostic passthrough of that first
 * attempt's result, not a signal that the close didn't happen.
 *
 * @return 0 on success, -EINVAL if `conn` is NULL/invalid, otherwise
 *         whatever the FIN's first send attempt returned
 */
dmod_dmtcp_api(1.0, int, _close, ( dmtcp_conn_t conn ));

/**
 * @brief Abortively close a connection (sends a RST, tears the TCB down
 *        immediately)
 *
 * `on_reset` fires (if registered), then the connection is freed - use
 * this instead of dmtcp_close() when you want RFC 793's abortive close,
 * not a graceful FIN exchange.
 *
 * @return 0 on success, -EINVAL if `conn` is NULL/invalid
 */
dmod_dmtcp_api(1.0, int, _abort, ( dmtcp_conn_t conn ));

#ifdef __cplusplus
}
#endif

#endif // DMTCP_H
